#### ArgpCD Applications ####
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dpskanpur/springapp-deployment.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
